name: Push to ACR using Managed Identity

env:
  # Configure the ACR login server and resource group
  REGISTRY_NAME: "boldgrouperacr"
  REGISTRY_URL: "boldgrouperacr.azurecr.io"
  RESOURCE_GROUP: "boldgrouper-rg"
  TAG: "latest"
  IMAGE_NAME: "api"
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

on:
  push:
    branches:
      - main

jobs:
  push-to-acr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          # Build your Docker image
          docker build -t $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:$TAG .
          
          # Login to Azure Container Registry using Azure credentials
          docker login $REGISTRY_NAME.azurecr.io --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET
          
          # Push Docker image to ACR
          docker push $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:$TAG
