name: Run Azure Login with OIDC

env:
  REGISTRY_NAME: "regularearwigacr"
  REGISTRY_URL: "regularearwigacr.azurecr.io"
  RESOURCE_GROUP: "regularearwig-rg"
  CLUSTER_NAME: "regularearwig-aks"
  PROJECT_NAME: "fitnessapp"
  PASSWORD: "8s15gPZ5F6OJkyVtELaANG9nktIUb3iRuM+jAcMGUY+ACRDmGH3h"
  TAG: "latest"
  K8S_DEPLOYMENT_NAME: "fitnessapp-deployment"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Azure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y azure-cli

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check Azure Login Status
      run: |
        az account show

    - name: Gets K8s context
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}

    - name: Build and Push Docker Image
      run: |
        docker login ${{ env.REGISTRY_URL }} -u ${{ env.REGISTRY_NAME }} -p ${{ env.PASSWORD }}
        docker build -t ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ env.TAG }} .
        docker push ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ env.TAG }}

        
    - name: Trigger Rolling Restart
      run: |
        kubectl rollout restart deployment/${{ env.K8S_DEPLOYMENT_NAME }} -n fitnessappnamespace
