name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Export ACR_SERVER
        run: |
          echo "ACR_SERVER=$ACR_SERVER" >> $GITHUB_ENV
          echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
      - 
        name: az login
        run: az login --identity
      # - 
      #   name: Azure login
      #   uses: azure/login@v2
      #   with:
      #     auth-type: IDENTITY          
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     enable-AzPSSession: true
      - 
        name: Login to ACR
        run: az acr login --name $ACR_NAME
      - 
        name: Print ACR_SERVER
        run: echo $ACR_SERVER
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.ACR_SERVER }}/api:latest