name: Push to ACR using Managed Identity

on:
  push:
    branches:
      - main

env:
  # Configure the ACR login server and resource group
  REGISTRY_NAME: "boldgrouperacr"
  REGISTRY_URL: "boldgrouperacr.azurecr.io"
  RESOURCE_GROUP: "boldgrouper-rg"
  TAG: "latest"
  IMAGE_NAME: "api"


jobs:
  push-to-acr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          # Build your Docker image (replace with your build commands)
          docker build -t ${{REGISTRY_NAME}}.azurecr.io/${{IMAGE_NAME:}}:${{TAG}} .
          
          # Push Docker image to ACR using Managed Identity
          az acr login --name ${{REGISTRY_NAME}}
          docker push ${{REGISTRY_NAME}}.azurecr.io/${{IMAGE_NAME:}}:${{TAG}}

